---
title: "GDP Project"
author: "s3638787 - Ravi Pandey"
date: "April 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}
library('tidyverse')
library("janitor")
```



```{r}
gdp <- read.csv("C:/Users/Wel/Downloads/GDP_Data.csv")

```

```{r}
str(gdp)

```

```{r}
gdp <- gdp %>% select(3:15)
head(gdp)
```

```{r}
gdp <- gdp[1:217,]
tail(gdp)
```



```{r}
gdp_tidy <- read.csv("C:/Users/Wel/Downloads/gdp_tidy.csv")
```

```{r}
gdp_tidy
```

```{r}
library(gganimate)
```

```{r}

gdp_formatted <- gdp_tidy %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = rank(-value),
         Value_rel = value/value[rank == 1],
         Value_lbl = paste0(" ",round(value/1e9))) %>%
  group_by(country_name) %>% 
  filter(rank <=10) %>%
  ungroup()

```

```{r}
staticplot=ggplot(gdp_formatted,aes(rank,group = country_name,
                  fill = as.factor(country_name), color = as.factor(country_name))) +
  geom_tile(aes(y=value/2,
                height = value,
                width = .5), alpha =.8, color = NA) +
  geom_text(aes(y=0, label = paste(country_name, " ")), vjust =0.2, hjust = 1, size =7) +
  geom_text(aes(y = value, label = Value_lbl, hjust = 0, size = 6)) +
  coord_flip(clip = 'off', expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y=element_blank(),
        legend.position='none',
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x=element_line(size = .2, color = 'grey'),
        panel.grid.minor.x=element_line(size = .2, color = 'grey'),
        plot.title=element_text(size = 20, hjust = 0.5, face = 'bold',color = "black",
        vjust = -1),
        plot.subtitle=element_text(size =20,hjust =0.5, face ='italic',color = "black"),
        plot.caption=element_text(size = 10,hjust = 0.5, face ='italic',color = "black"),
        plot.background=element_blank(),
        plot.margin = margin(3,6,6,7,"cm"))
```

```{r}
anim = staticplot + transition_states(year,transition_length = 4,state_length = 1) +
  view_follow(fixed_x = TRUE) +
  labs(title = "GDP per Year : {closest_state}",
       subtitle = "Top 10 Countries",
       caption = "GDP in Billions USD | Data Source: World Bank Data")
      
```

```{r}
library(gifski)
library(png)
animate(anim, 100, fps = 25, width = 800, height = 600,
        renderer = gifski_renderer("Barchart.gif"))
```

```{r}
animate(anim, 200, fps = 20,  width = 1200, height = 1000, 
        renderer = ffmpeg_renderer()) -> for_mp4

anim_save("animation.mp4", animation = for_mp4 )
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

